Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database

Private Sub Form_Open(Cancel As Integer)
'Put all under comment for further review.. 251114
'    Me.OrderBy = "T_PolaLubang.JumlahLubang"
'    Me.OrderByOn = True
'    Me.AllowAdditions = False
'    Me.AllowEdits = False
'    Me.AllowDeletions = False
'    If (Nz(Me.OpenArgs) <> 0) Then
'        Me!T_PolaLubang.JumlahLubang.SetFocus
'        DoCmd.FindRecord Me.OpenArgs
'    End If
End Sub
