CREATE TABLE [T_ProfilKeping] (
  [KepingAutoID] AUTOINCREMENT,
  [KepingID] VARCHAR (255) CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [BlankoKepingAutoID] LONG CONSTRAINT [T_BlankoKepingT_ProfilKeping] REFERENCES [T_BlankoKeping] ([BlankoKepingAutoID]),
  [DeskripsiProfilKeping] VARCHAR (255),
  [PolaLubangID] LONG CONSTRAINT [T_UkuranPolaLubangT_ProfilKeping] REFERENCES [T_UkuranPolaLubang] ([PolaLubangID]),
  [UkuranLubangID] LONG CONSTRAINT [T_UkuranLubangT_ProfilKeping] REFERENCES [T_UkuranLubang] ([UkuranLubangID]),
  [RivetID] LONG CONSTRAINT [T_UkuranRivetT_ProfilKeping] REFERENCES [T_UkuranRivet] ([RivetID]),
  [Indikator-Lis] BIT,
  [Coak] BIT,
  [Koak] BIT,
  [Catatan] LONGTEXT,
  [ImageCode] VARCHAR (255),
  [NoteGambar] LONGTEXT,
  [LubangFlag] BIT,
  [TebalTipisFlag] BIT,
  [DiameterDrum_deprecated] LONG,
  [PolaLubangID_deprecated2] LONG,
  [PolaLubangID_deprecated] LONG,
  [JumlahLubang_deprecated] LONG,
  [UkuranRivetID_deprecated] VARCHAR (255),
  [Tebal/Tipis_deprecated] VARCHAR (255),
  [JenisRivet_deprecated] VARCHAR (255),
  [UkuranRivet_deprecated] VARCHAR (255),
  [UkuranLubang_deprecated] LONG,
  [Lebar_deprecated] VARCHAR,
  [Panjang_deprecated] VARCHAR,
  [Tebal_deprecated] VARCHAR (255)
)
