CREATE TABLE [T_ProdukOEM] (
  [OEMID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [SetID] LONG,
  [Manufaktur] LONG,
  [KodeOEM] VARCHAR (255),
  [CatatanOEM] VARCHAR (255)
)
